# Generated by Django 5.0.2 on 2026-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_attribute_tag_alter_category_options_attributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
